### ISSUE TITLE
Add support for folders

### ISSUE THREAD

**Issue by UnknownSilicon** [jakebacker/googlephotos-filestorage#5]
Currently, folders do not behave when uploaded. This should add support to zip the folder and upload it as if it were a normal file (this might already be working), then download it and unzip it normally.

**Comment by bshin100** [comment]
Nice

**Comment by dangleweed** [comment]
Would be a great feature. I tested this without success.

**Comment by UnknownSilicon** [comment]
This has been fixed in the master branch. It will be in the next release.

**Comment by dangleweed** [comment]
Cool. thanks!

**Comment by dangleweed** [comment]
Works really well in the new release. Many thanks.
